services:
  django:
    build: ./backend/
    expose:
      8000
    environment:
      - OWM_API_KEY=${OWM_API_KEY}
      - DEBUG=${DEBUG}
    depends_on:
      db:
        condition: service_healthy

  postgres:
    build: ./
secrets:
  db-password:
    file: secrets/db_password.txt
  owm-key:
    file: secrets/owm_api_key.txt