services:
  django:
    build: ./backend/
    ports:
      - "8000:8000"
    environment:
      OWM_API_KEY: ${OWM_API_KEY}
      DEBUG: ${DEBUG}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - ./backend/:/app
    

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  vue:
    build: ./frontend/
    ports:
      - "5173:5173"
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./frontend/:/app/:delegated"
      - "/app/node_modules"
    depends_on:
      - django

volumes:
  postgres_volume: